### ISSUE TITLE
port1 & port2 question Jerry's job

### ISSUE THREAD

**Issue by icey0230** [Jerry375716121/KFC#15]
分成file写， 客户端一个file，店员端一个file， 想想。 就是两个端口需要同时运行

**Comment by Jerry375716121** [comment]
一定要这么写？

先把我们这个方法的代码完善一下吧

luna咋评价我们？

**Comment by icey0230** [comment]
没有评价啥， 就是一定要用file写（）

**Comment by icey0230** [comment]
add food的bug和input validation，我明天写一下。 file我没怎么搞懂， 你去问问luna比较好
